### ISSUE TITLE
Intellij fails to launch after installing Eclipser

### ISSUE THREAD

**Issue by stijnvanpoucke** [kukido/eclipser#20]
I've got the following exception:

Internal error. Please report to http://jb.gg/ide/critical-startup-errors

```
java.lang.AssertionError: Unexpected node Pythonid; nodes=[spy-js, org.jetbrains.settingsRepository, org.jetbrains.plugins.terminal, org.jetbrains.plugins.stylus, org.jetbrains.plugins.sass, org.jetbrains.plugins.remote-run, org.jetbrains.plugins.less, org.jetbrains.plugins.haml, org.jetbrains.plugins.github, org.jetbrains.kotlin, org.jetbrains.java.decompiler, org.jetbrains.idea.maven.ext, org.jetbrains.idea.maven, org.jetbrains.idea.eclipse, org.intellij.plugins.markdown, org.intellij.intelliLang, org.editorconfig.editorconfigjetbrains, org.coffeescript, net.nicoulaj.idea.markdown, cucumber-java, cucumber, com.vladsch.idea.multimarkdown, com.kukido.eclipser, com.jetbrains.restWebServices, com.jetbrains.restClient, com.jetbrains.plugins.webDeployment, com.jetbrains.php, com.intellij.vaadin, com.intellij.uiDesigner, com.intellij.ui-designer-new, com.intellij.thymeleaf, com.intellij.tasks.timeTracking, com.intellij.tasks, com.intellij.spring.websocket, com.intellij.spring.security, com.intellij.spring.osgi, com.intellij.spring.mvc, com.intellij.spring.integration, com.intellij.spring.data, com.intellij.spring.boot, com.intellij.spring, com.intellij.properties, com.intellij.plugins.html.instantEditing, com.intellij.persistence, com.intellij.modules.xml, com.intellij.modules.xdebugger, com.intellij.modules.vcs, com.intellij.modules.ultimate, com.intellij.modules.sql, com.intellij.modules.remoteServers, com.intellij.modules.python, com.intellij.modules.platform, com.intellij.modules.lang, com.intellij.modules.json, com.intellij.modules.java, com.intellij.modules.database, com.intellij.modules.all, com.intellij.jsp, com.intellij.jboss.core, com.intellij.jboss.arquillian, com.intellij.javaee.webSocket, com.intellij.javaee.view, com.intellij.javaee.extensions, com.intellij.javaee, com.intellij.java-i18n, com.intellij.gwt, com.intellij.guice, com.intellij.flex, com.intellij.dsm, com.intellij.dmserver, com.intellij.diagram, com.intellij.database, com.intellij.css, com.intellij.copyright, com.intellij.cdi, com.intellij.beanValidation, com.intellij.aspectj, com.intellij.aop, com.intellij, XSLT-Debugger, XPathView, W3Validators, TestNG-J, Refactor-X, QuirksMode, Osmorc, NodeJS, Mongo Plugin, Karma, Jetty, JavaScriptDebugger, JavaScript, Java EE: Web Services (JAX-WS), JUnit, JSIntentionPowerPack, HtmlTools, GlassFish, Git4Idea, Emma, DevKit, Coverage, ByteCodeViewer, BashSupport, AntSupport, AngularJS]
    at com.intellij.util.graph.GraphGenerator.buildOuts(GraphGenerator.java:55)
    at com.intellij.util.graph.GraphGenerator.<init>(GraphGenerator.java:36)
    at com.intellij.util.graph.GraphGenerator.create(GraphGenerator.java:40)
    at com.intellij.ide.plugins.PluginManagerCore.a(PluginManagerCore.java:622)
    at com.intellij.ide.plugins.PluginManagerCore.b(PluginManagerCore.java:1167)
    at com.intellij.ide.plugins.PluginManagerCore.a(PluginManagerCore.java:1334)
    at com.intellij.ide.plugins.PluginManagerCore.getPlugins(PluginManagerCore.java:105)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:328)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:94)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:454)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:446)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:60)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by kukido** [comment]
Hi! Thank you for reporting the issue! 

In order to identify the issue, please let me know the following:
* what version of IntelliJ are you using
* what version of Eclipser have you installed
* how was Eclipser installed
* what happens if you uninstall just Eclipser plugin

**Comment by stijnvanpoucke** [comment]
I'm using Intellij 15.2 on OS X 10.11.2
I've installed eclipser 0.7.1 via preferences > plugins > browse repositories
Nothing changed by uninstalling eclipser from the plugins directory but I've fixed it by removing python from that directory and installing eclipser again...

**Comment by kukido** [comment]
Well, I suspected it was not Eclipser. As the error says "Unexpected node Pythonid".
